version: "3.9"

services:
  app:
    image: node:22-alpine
    working_dir: /app
    container_name: owieczkowy-bot
    environment:
      - BOT_TOKEN=${DISCORD_TOKEN}
      - BOT_PREFIX=${BOT_PREFIX}
      - BOT_YT_DLP=${BOT_YT_DLP}
      - BOT_ID=${BOT_ID}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev